# Use the official MySQL image from the Docker Hub
FROM mysql:5.7

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=cmsdb
ENV MYSQL_USER=dbuser


# Expose the MySQL port
EXPOSE 3306
